
name: Testing Deply A simple php file

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy repository to production server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy repository via rsync
      # rsync is a powerful tool for synchronizing files
      run: |
        rsync -avz --delete \
          --exclude='.git*' \
          --exclude='.github*' \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOYING_PATH }}
        echo "✅ Deployment successful!"